[System.Serializable]
public enum GameState
{
    LOADING_MAIN_MENU,
    IN_MAIN_MENU,
    LOADING_GAME,
    LOADING_NEXT_GAMEPLAY_LEVEL,
    PLAYING,
    PAUSED,
    RETURNING_TO_MAIN_MENU,
    PLAYER_DEFEAT,
    LEVEL_COMPLETED,
    SHUTTING_DOWN
    
}
